version: "3.8"

services:
  cms_frontend:
    container_name: cms_frontend
    build: ./cms_frontend
    volumes:
      # Note must include node_modules as a seperate volume
      - '/app/node_modules'
      - './cms_frontend:/app'
    stdin_open: true
    ports:
      - 3000:3000
  backend:
    container_name: go_backend
    build: ./Backend
    volumes:
      - './Backend:/go/src/DiffSync'
      - './Backend/${GO_MOD}:/go/src/DiffSync/go.mod'
    ports:
      - 8080:8080
  db:
    container_name: pg_container
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - './postgres/infile:/infile'
      - 'pg_data:/var/lib/postgresql/data'
volumes:
  pg_data:

